"""add game_catalog

Revision ID: 0b1f9f8f9a6e
Revises: 2e86c6833d73
Create Date: 2026-02-15 17:25:36.718646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1f9f8f9a6e'
down_revision = '2e86c6833d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_catalog',
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('supported_languages', sa.Text(), nullable=True),
    sa.Column('full_audio_languages', sa.Text(), nullable=True),
    sa.Column('developers', sa.Text(), nullable=True),
    sa.Column('publishers', sa.Text(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('header_image', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('windows', sa.Boolean(), nullable=True),
    sa.Column('mac', sa.Boolean(), nullable=True),
    sa.Column('linux', sa.Boolean(), nullable=True),
    sa.Column('metacritic_score', sa.Integer(), nullable=True),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('appid')
    )
    with op.batch_alter_table('game_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_catalog_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_catalog_name'))

    op.drop_table('game_catalog')
    # ### end Alembic commands ###
