"""init tables

Revision ID: 2e86c6833d73
Revises: 
Create Date: 2026-02-12 22:24:02.049833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e86c6833d73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_users_email'), ['email'], unique=True)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_user_id', sa.Integer(), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_appid'), ['appid'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_auth_user_id'), ['auth_user_id'], unique=False)

    op.create_table('user_game_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steamid', sa.String(length=32), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('playtime_forever', sa.Integer(), nullable=True),
    sa.Column('playtime_2weeks', sa.Integer(), nullable=True),
    sa.Column('last_played', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steamid', 'appid', name='uq_user_game')
    )
    with op.batch_alter_table('user_game_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_game_stats_appid'), ['appid'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_game_stats_steamid'), ['steamid'], unique=False)

    op.create_table('steam_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_user_id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.String(length=32), nullable=False),
    sa.Column('persona', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('last_sync_ts', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('steam_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_steam_profiles_auth_user_id'), ['auth_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_steam_profiles_steamid'), ['steamid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steam_profiles_steamid'))
        batch_op.drop_index(batch_op.f('ix_steam_profiles_auth_user_id'))

    op.drop_table('steam_profiles')
    with op.batch_alter_table('user_game_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_game_stats_steamid'))
        batch_op.drop_index(batch_op.f('ix_user_game_stats_appid'))

    op.drop_table('user_game_stats')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_auth_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_appid'))

    op.drop_table('feedback')
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_users_email'))

    op.drop_table('auth_users')
    # ### end Alembic commands ###
