"""update database

Revision ID: 3f8b2bb59e3b
Revises: f24dc9aa9472
Create Date: 2026-02-15 20:03:33.816138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8b2bb59e3b'
down_revision = 'f24dc9aa9472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_context_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_user_id', sa.Integer(), nullable=False),
    sa.Column('time_available_min', sa.Integer(), nullable=False),
    sa.Column('energy_level', sa.String(length=16), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('social_mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_context_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_context_logs_auth_user_id'), ['auth_user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_user_id', sa.Integer(), nullable=False),
    sa.Column('genre_weights', sa.Text(), nullable=True),
    sa.Column('comfort_bias', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_auth_user_id'), ['auth_user_id'], unique=True)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_snapshot', sa.Text(), nullable=True))

    with op.batch_alter_table('game_catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_session_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('multiplayer_mode', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_catalog', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('multiplayer_mode')
        batch_op.drop_column('avg_session_minutes')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('context_snapshot')

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_auth_user_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('user_context_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_context_logs_auth_user_id'))

    op.drop_table('user_context_logs')
    # ### end Alembic commands ###
