"""widen game_catalog text columns

Revision ID: 5a4e374bfcca
Revises: 0b1f9f8f9a6e
Create Date: 2026-02-15 17:37:56.762689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a4e374bfcca'
down_revision = '0b1f9f8f9a6e'
branch_labels = None
depends_on = None


def upgrade():
    if op.get_bind().dialect.name == "sqlite":
        # SQLite TEXT is already effectively unbounded for this use case.
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_catalog', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('supported_languages',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('categories',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('genres',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('document',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().dialect.name == "sqlite":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_catalog', schema=None) as batch_op:
        batch_op.alter_column('document',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('genres',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('categories',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('supported_languages',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('about',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
