"""widen game_catalog name and text fields

Revision ID: f24dc9aa9472
Revises: 5a4e374bfcca
Create Date: 2026-02-15 18:01:55.192584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f24dc9aa9472'
down_revision = '5a4e374bfcca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_catalog', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('full_audio_languages',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('developers',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('publishers',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('header_image',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_catalog', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('header_image',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('publishers',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('developers',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('full_audio_languages',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
